name: Bug Report
description: Create a bug report to help us improve Ultimate RP Pack
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1.
                2.
                3.
                ...
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report and Log
            description: If applicable, please add a **link** to the relevant crash report and latest.log that was created when this issue occured using a site such as pastebin, hastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue
        validations:
            required: false
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            placeholder: Windows 11
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            options:
                - "1.12"
                - "1.16"
                - "1.19"
        validations:
            required: true
    -   type: input
        attributes:
            label: Modpack Version
            description: The Modpack version you were using, for example 3.1.0
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Have you added any other mods you added to our packs? if yes please list any other mods.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this bug report. Expect to receive a response soon"